instrument_aliases:
  "сбербанк": "SBER"
  "сбера": "SBER"
  "сбер": "SBER"
  "газпром": "GAZP"
  "яндекс": "YNDX"
  "роснефть": "ROSN"
  "роснефти": "ROSN"
  "норникель": "GMKN"
  "норникеля": "GMKN"
  "русгидро": "HYDR"
  "мосбиржа": "MOEX"
  "мечел": "MTLR"
  "втб": "VTBR"
  "фосагро": "PHOR"
  "аэрофлот": "AFLT"
