endpoints:
- schema: Auth
  method: POST
  path: /v1/sessions
- schema: TokenDetails
  method: POST
  path: /v1/sessions/details/
- schema: GetAccount
  method: GET
  path: /v1/accounts/account_id
- schema: Trades
  method: GET
  path: /v1/accounts/account_id/trades
- schema: Transactions
  method: GET
  path: /v1/accounts/account_id/transactions
- schema: Assets
  method: GET
  path: /v1/assets
- schema: Clock
  method: GET
  path: /v1/assets/clock
- schema: Exchanges
  method: GET
  path: /v1/exchanges
- schema: GetAsset
  method: GET
  path: /v1/assets/SBER@MISX/
- schema: GetAssetParams
  method: GET
  path: /v1/assets/SBER@MISX/params
- schema: OptionsChain
  method: GET
  path: /v1/assets/YDEX@MISX/options
- schema: Schedule
  method: GET
  path: /v1/assets/YDEX@MISX/schedule
- schema: PlaceOrder
  method: POST
  path: /v1/accounts/account_id/orders
- schema: CancelOrder
  method: DELETE
  path: /v1/accounts/{account_id}/orders/{order_id}
- schema: GetOrders
  method: GET
  path: /v1/accounts/account_id/orders
- schema: GetOrder
  method: GET
  path: /v1/accounts/account_id/orders/order_id
- schema: Bars
  method: GET
  path: /v1/instruments/YDEX@MISX/bars
- schema: LastQuote
  method: GET
  path: /v1/instruments/YDEX@MISX/quotes/latest
- schema: LatestTrades
  method: GET
  path: /v1/instruments/YDEX@MISX/trades/latest
- schema: OrderBook
  method: GET
  path: /v1/instruments/YDEX@MISX/orderbook
